name: range2
description: Dart2 compatible python-like range() function implemented using sync*.
version: 0.1.1
homepage: https://github.com/xtyxtyx/range2
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
